//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiQRAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPOSASIGNACIONTEMP
    {
        public long ID { get; set; }
        public string CABEZALNOMBRE { get; set; }
        public string CABEZALPLACA { get; set; }
        public Nullable<bool> CABEZALPEROPERACION { get; set; }
        public Nullable<System.DateTime> CABEZALFECHAOPERACION { get; set; }
        public Nullable<bool> CABEZALLICENCIA { get; set; }
        public Nullable<bool> CABEZALBOLETAREVISION { get; set; }
        public Nullable<System.DateTime> CABEZALFECHABOLETAREVIISON { get; set; }
        public Nullable<bool> CABEZALEXTINTOR { get; set; }
        public Nullable<System.DateTime> CABEZALFECHAEXTINTOR { get; set; }
        public Nullable<int> CABEZALCANTIDADEXTINTOR { get; set; }
        public Nullable<bool> CABEZALPALA { get; set; }
        public Nullable<bool> CABEZALABOSRVENTE { get; set; }
        public Nullable<bool> CABEZALTACO { get; set; }
        public Nullable<bool> CABEZALCUNIA { get; set; }
        public Nullable<bool> CABEZALMARTILLO { get; set; }
        public Nullable<bool> CABEZALEXPOXY { get; set; }
        public Nullable<bool> CABEZALCUNSEG { get; set; }
        public Nullable<int> CABEZALCANTIDADCUNSEG { get; set; }
        public Nullable<bool> CABEZALBOTIQUIN { get; set; }
        public Nullable<bool> CABEZALFOCO { get; set; }
        public Nullable<bool> CABEZALLLANTAS { get; set; }
        public Nullable<bool> CABEZALLUCES { get; set; }
        public Nullable<bool> CABEZALSNFUGAS { get; set; }
        public Nullable<bool> CABEZALCHASIS { get; set; }
        public Nullable<bool> CABEZALCINTURON { get; set; }
        public Nullable<bool> CABEZALMASSHITCH { get; set; }
        public Nullable<bool> CABEZALALARMA { get; set; }
        public Nullable<bool> CABEZALGPS { get; set; }
        public Nullable<bool> CABEZALINTCABINA { get; set; }
        public Nullable<bool> CABEZALEXTCARROCERIA { get; set; }
        public Nullable<bool> CABEZALLIMPIEZA { get; set; }
        public Nullable<bool> CABEZALPARLANTES { get; set; }
        public Nullable<int> CABEZALCANTIDADPARLANTES { get; set; }
        public Nullable<bool> CABEZALRADIO { get; set; }
        public Nullable<int> CABEZALCANTIDADRADIO { get; set; }
        public Nullable<bool> CABEZALCOLCHON { get; set; }
        public Nullable<bool> CABEZALTAPIZADO { get; set; }
        public string CISTERNANOMBRE { get; set; }
        public string CISTERNAPLACA { get; set; }
        public Nullable<bool> CISTERNAPEROPERACION { get; set; }
        public Nullable<System.DateTime> CISTERNAFECHAOPERACION { get; set; }
        public Nullable<bool> CISTERNAREVISION { get; set; }
        public Nullable<System.DateTime> CISTERNAFECHAREVISION { get; set; }
        public Nullable<bool> CISTERNACALIBRACION { get; set; }
        public Nullable<bool> CISTERNAEXTINTOR { get; set; }
        public Nullable<System.DateTime> CISTERNAEXTINTORA { get; set; }
        public Nullable<System.DateTime> CISTERNAEXTINTORB { get; set; }
        public Nullable<bool> CISTERNACUBETA { get; set; }
        public Nullable<bool> CISTERNAEMBUDO { get; set; }
        public Nullable<bool> CISTERNATIGHFILL { get; set; }
        public Nullable<bool> CISTERNACONO { get; set; }
        public Nullable<int> CISTERNACANTIDADCONO { get; set; }
        public Nullable<bool> CISTERNAMANGUERAS { get; set; }
        public Nullable<int> CISTERNACANTIDADMANGUERAS { get; set; }
        public Nullable<bool> CISTERNALLANTAS { get; set; }
        public Nullable<bool> CISTERNACHASIS { get; set; }
        public Nullable<bool> CISTERNAGRADAS { get; set; }
        public Nullable<bool> CISTERNALINEAS { get; set; }
        public Nullable<bool> CISTERNACINTA { get; set; }
        public Nullable<bool> CISTERNAMANHOLES { get; set; }
        public Nullable<bool> CISTERNALODERAS { get; set; }
        public Nullable<bool> CISTERNATERMINALES { get; set; }
        public Nullable<bool> CISTERNALUCES { get; set; }
        public Nullable<bool> CISTERNACONDUCTORES { get; set; }
        public Nullable<bool> CISTERNAESTMANGUERA { get; set; }
        public Nullable<bool> CISTERNATANQUE { get; set; }
    }
}
